### ISSUE TITLE
GC interrupt enable register not writable by M-mode

### ISSUE THREAD

**Issue by allenjbaum** [robfinch/Cores#4]
IF a CSR is accessible in some mode and is RW, then it is writable in that mode.

You are proposing a CSR which is accessible in all modes,  but can be written (at least set) only by U-mode, which appears to be a spec violation ( and also a viirtualization hole, since it can be used to discover which mode the code is operating in

**Comment by robfinch** [comment]
I have switched the proposal so that the CSR may be updated by any mode.
